DROP TABLE IF EXISTS teams;
USE nba
DROP TABLE IF EXISTS teams;
CREATE TABLE IF NOT EXISTS teams (
  `id` INT NOT NULL PRIMARY KEY,
  `name` VARCHAR(50) NOT NULL,
  `code` VARCHAR(5) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `logo` VARCHAR(255) NOT NULL,
  `conference` VARCHAR(20) NOT NULL
);